services:
  mysql:
    container_name: mysql_ksero_1
    image: 'mysql'
    environment:
      - 'MYSQL_DATABASE=ksero_db'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  products-microservice:
    container_name: products_microservice_1
    image: products-ms-image
    environment:
      - 'MY_HOST_SPRING=jdbc:mysql://mysql:3306/ksero_db?useSSL=true&createDatabaseIfNotExist=true'
    ports:
      - "8200:8200"
    expose:
      - '8200'
    restart: on-failure
  wholesalers-microservice:
    container_name: wholesaler_microservice_1
    image: wholesalers-ms-image
    environment:
      - 'MY_HOST_SPRING=jdbc:mysql://mysql:3306/ksero_db?useSSL=true&createDatabaseIfNotExist=true'
    ports:
      - "8101:8101"
    expose:
      - '8101'
    restart: on-failure
  retailers-microservice:
    container_name: retailers_microservice_1
    image: retailers-ms-image
    environment:
      - 'MY_HOST_SPRING=jdbc:mysql://mysql:3306/ksero_db?useSSL=true&createDatabaseIfNotExist=true'
    ports:
      - "8102:8102"
    expose:
      - '8102'
    restart: on-failure
  wholesaler-orders-microservice:
    container_name: wholesaler_orders_microservice_1
    image: wholesaler-orders-ms-image
    environment:
      - 'MY_HOST_SPRING=jdbc:mysql://mysql:3306/ksero_db?useSSL=true&createDatabaseIfNotExist=true'
    ports:
      - "8090:8090"
    expose:
      - '8090'
    restart: on-failure